// import Nav from '@/components/nav/Nav';
// import '../assets/css/main.css'
// import '../assets/css/style.css'
// import Footer from '@/components/footer/Footer';
// import SubNav from '@/components/nav/SubNav';

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body >
//         <Nav />
//         <SubNav />
//         {children}
//         <Footer />
//       </body>
//     </html>
//   );
// }


"use client"; 
import { usePathname } from "next/navigation";
import Nav from '@/components/nav/Nav';
import Footer from '@/components/footer/Footer';
import SubNav from '@/components/nav/SubNav';
import '../assets/css/main.css';
import '../assets/css/style.css';
import Providers from '@/components/Providers';

export default function RootLayout({ children }) {
  const pathname = usePathname();
  
  const isAuthPage = pathname === "/auth/login" || pathname === "/auth/signup" || pathname === "/auth/forgetpassword" || pathname === "/auth/otp" || pathname === "/auth/changepassword";

  return (
    <html lang="en">
      <body>
        <Providers>
          {!isAuthPage && <Nav />}
          {!isAuthPage && <SubNav />}
          
          <main>{children}</main>
          
          {!isAuthPage && <Footer />}
        </Providers>
      </body>
    </html>
  );
}