import Nav from '@/components/nav/Nav';
import '../assets/css/main.css'
import '../assets/css/style.css'
import Footer from '@/components/footer/Footer';
import SubNav from '@/components/nav/SubNav';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Nav />
        <SubNav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
